### ISSUE TITLE
Cannot find module `gulp` (after upgrading from 1.3 -> 1.4)

### ISSUE THREAD

**Issue by ftes** [eirslett/frontend-maven-plugin#658]
**bug**

**What is the current behavior?**
Log output
```
[INFO] --- frontend-maven-plugin:1.4:install-node-and-yarn (install node and yarn) @ portal ---
[INFO] Running 'bower install' in <src>
...
[INFO] --- frontend-maven-plugin:1.4:gulp (gulp build) @ portal ---
[INFO] Running 'gulp build' in <src>
[ERROR] module.js:471
[ERROR]     throw err;
[ERROR]     ^
[ERROR] 
[ERROR] Error: Cannot find module '<target>/node_modules/gulp/bin/gulp'
[ERROR]     at Function.Module._resolveFilename (module.js:469:15)
[ERROR]     at Function.Module._load (module.js:417:25)
[ERROR]     at Module.runMain (module.js:604:10)
[ERROR]     at run (bootstrap_node.js:394:7)
[ERROR]     at startup (bootstrap_node.js:149:9)
[ERROR]     at bootstrap_node.js:509:3
</code>
</details>
```

**If the current behavior is a bug, please provide the steps to reproduce.**

pom.xml:
```
<plugin>
	<groupId>com.github.eirslett</groupId>
	<artifactId>frontend-maven-plugin</artifactId>
	<version>1.4</version>

	<configuration>
		<workingDirectory>src/web</workingDirectory>
		<installDirectory>target</installDirectory>
	</configuration>

	<executions>
		<execution>
			<id>install node and yarn</id>
			<goals>
				<goal>install-node-and-yarn</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<nodeVersion>v6.9.1</nodeVersion>
				<yarnVersion>v0.17.9</yarnVersion>
			</configuration>
		</execution>
		<execution>
			<id>yarn install</id>
			<goals>
				<goal>yarn</goal>
			</goals>
			<phase>generate-resources</phase>
		</execution>
		<execution>
			<id>bower install</id>
			<goals>
				<goal>bower</goal>
			</goals>
		</execution>
		<execution>
			<id>gulp build</id>
			<goals>
				<goal>gulp</goal>
			</goals>
			<phase>generate-resources</phase>
			<configuration>
				<arguments>build</arguments>
			</configuration>
		</execution>
		<execution>
			<id>gulp test</id>
			<goals>
				<goal>gulp</goal>
			</goals>
			<phase>test</phase>
			<configuration>
				<arguments>test</arguments>
				<environmentVariables>
					<BABEL_ENV>test</BABEL_ENV>
				</environmentVariables>
			</configuration>
		</execution>
	</executions>
</plugin>
```

**What is the expected behavior?**
`v1.3` works as expected, with this log output
```
[INFO] --- frontend-maven-plugin:1.3:install-node-and-yarn (install node and yarn) @ portal ---
[INFO] Installing node version v6.9.1
...
[INFO] Installing Yarn version v0.17.9
...
[INFO] --- frontend-maven-plugin:1.3:yarn (yarn install) @ portal ---
[INFO] Running 'yarn ' in <src>
[INFO] yarn install v0.17.9
...
[INFO] --- frontend-maven-plugin:1.3:bower (bower install) @ portal ---
...
```

**Please mention your frontend-maven-plugin and operating system version.**
Arch Linux
frontend-maven-plugin `1.4`

**Comment by alex-courtis** [comment]
Duplicate of #590 

Fixed by #649
