### PR TITLE
Corrects gulp execution path

### PR DESCRIPTION
**Pull request by mtraynham**
**Summary**
#586 - gulp doesn't work in frontend-maven-plugin 1.4
#590 - Cannot find module Gulp when change workingDirectory

#590 mentions what to do.

Seems like there may have been conflicting changes when performing:
#536 (PR #558) - Failed to execute goal com.github.eirslett:frontend-maven-plugin:0.0.22:gulp
#434 - Use InstallDirectory to locate node tasks instead of the WorkingDirectory

Reverting the change in #558

**Tests and Documentation**
Will add info to CHANGELOG if needed

### CODE REVIEW

**Comment by alex-courtis** [comment]
Hi

Please merge this branch and release the plugin - it's blocking gulp execution )-:

**Comment by eirslett** [comment]
thanks!

**Comment by alex-courtis** [comment]
Thanks for merging @eirslett 

Can you please release the plugin to maven central, so that we may use this fix.

**Comment by piotrtomiak** [comment]
+1

**Comment by rzymek01** [comment]
@eirslett please take a look at #661. I believe it fits nicely as a general solution for this kind of problems.

**Comment by harris1127** [comment]
Is this yet released to maven central, it seems 1.6 is still causing an issue with gulp not being found?

**Comment by pauloallonso** [comment]
Hi, is this already released to maven central ? Using 1.6 version here is still not finding gulp. Thanks

**Comment by mtraynham** [comment]
Anyone looking for a stupid simple workaround, don't use the `gulp` goal.  Use the `yarn` or `npm` goals to invoke npm scripts and call gulp from an npm script.

pom.xml
```xml
                    <execution>
                        <id>test</id>
                        <phase>test</phase>
                        <goals>
                            <goal>yarn</goal>
                        </goals>
                        <configuration>
                            <arguments>run lint test</arguments>
                        </configuration>
                    </execution>
```
package.json
```json
    "scripts": {
        "build": "gulp build",
        "release": "gulp release",
        "lint": "gulp lint",
        "test": "gulp test"
    },
```

It's hokey, but it works, and it's no different than a web developer just running `yarn run build`.
